export default {
    TEXT: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin sapien vitae est egestas vestibulum. Ut condimentum sagittis dolor eu bibendum. Ut orci dui, venenatis vel erat sit amet, dapibus efficitur libero. Nunc suscipit sit amet purus sed maximus. Praesent suscipit sapien ac interdum lobortis. Mauris porttitor varius eros, id interdum purus auctor a. Nulla suscipit ante lacus, id lobortis purus euismod mattis. Aenean vel sapien imperdiet nulla sollicitudin porttitor. Phasellus consectetur gravida porta. Praesent in dapibus lectus, nec gravida felis. Curabitur ultricies, mauris ut sodales varius, leo est porta urna, nec malesuada nibh mi nec mauris. Sed quis massa eget ante interdum ullamcorper ut non arcu. Nulla imperdiet leo eu magna accumsan, ut molestie tortor pharetra. Ut eget blandit purus, vel vestibulum arcu. Curabitur aliquam tincidunt felis, eu molestie diam.

    Integer eu elementum dui. Quisque eget tempus magna. Duis pretium nisl elit, eu fringilla lacus vehicula ac. Mauris porttitor magna tristique rutrum convallis. Cras id orci sit amet metus vehicula sollicitudin. Ut quis turpis ac eros cursus aliquam sit amet sed libero. Sed aliquet massa in dignissim feugiat. Morbi consectetur dignissim nulla blandit ornare. Morbi egestas nibh non orci fermentum sodales. Aenean sit amet dolor quis leo posuere bibendum a a justo. Vivamus pretium, ipsum eget tincidunt rutrum, dui magna ultricies lectus, eget rhoncus nisl ante ac lorem. Donec nulla magna, consequat eget accumsan at, luctus quis ante. Praesent vitae dui vitae leo gravida egestas. Maecenas quis dictum ante.
    
    Etiam ac eros quis turpis pharetra pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique lorem et nunc mattis, vel mollis quam vestibulum. Sed tincidunt est a ipsum vehicula, eget tincidunt sapien volutpat. Maecenas vel risus ante. Mauris suscipit nisl quis eros tristique tincidunt. Fusce vel vulputate mi. Sed et viverra magna. Fusce vestibulum risus suscipit magna facilisis placerat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus vulputate ante eros, ut fringilla ipsum accumsan vitae. Maecenas laoreet ut massa a venenatis. Nam lacinia, sem faucibus congue facilisis, velit libero gravida justo, quis lobortis ante libero ac enim. Pellentesque id pulvinar est, vitae dictum purus.
    
    Duis a nisi feugiat, egestas eros eget, hendrerit leo. Quisque non arcu purus. Morbi non iaculis quam. Mauris id neque dolor. Pellentesque eget mauris sit amet nunc molestie tempor sit amet quis massa. Nam at elit sapien. Quisque ac leo vel lectus faucibus commodo a eu nulla. Donec interdum ut libero quis euismod. Sed vehicula ullamcorper augue, ut tincidunt velit interdum vitae. Sed lobortis ut mauris rhoncus commodo.
    
    Aenean in augue congue turpis porta gravida. Phasellus blandit convallis imperdiet. Duis in posuere ipsum. Ut non ex laoreet, pretium purus ut, dapibus tellus. Integer vitae ipsum pellentesque, placerat justo sit amet, viverra nisi. Phasellus sodales est et elementum congue. Curabitur non urna viverra justo vehicula sodales egestas at nulla. Phasellus elementum libero quis elit posuere, non venenatis turpis consectetur. Curabitur feugiat risus leo, quis ornare dui cursus eu. Etiam id elit ac urna rutrum dapibus eu eu erat. Suspendisse mattis ex eu sem efficitur placerat. Etiam maximus ornare metus ut suscipit. Nunc quis efficitur ipsum. Sed dictum ac odio in accumsan. Maecenas fringilla, nisi ac lobortis vehicula, lacus massa semper dolor, at lobortis nisl diam quis mi. Nunc congue massa sit amet nibh finibus porttitor.`
}